
@echo off
net stop ALG
net stop PeerDistSvc
net stop NfsClnt
net stop dmwappushsvc
net stop MapsBroker
net stop Fax
net stop lfsvc
net stop hns
net stop HvHost
net stop vmickvpexchange
net stop vmicguestinterface
net stop vmicshutdown
net stop vmicheartbeat
net stop vmcompute
net stop vmicvmsession
net stop vmicrdv
net stop vmictimesync
net stop vmms
net stop vmicvss
net stop IISADMIN
net stop irmon
net stop SharedAccess
net stop MSiSCSI
net stop SmsRouter
net stop CscService
net stop WpcMonSvc
net stop SEMgrSvc
net stop PhoneSvc
net stop RpcLocator
net stop SensrSvc
net stop SensorService
net stop ScDeviceEnum
net stop SCPolicySvc
net stop SNMPTRAP
net stop TabletInputService
net stop WFDSConSvc
net stop FrameServer
net stop wisvc
net stop WMPNetworkSvc
net stop icssvc
net stop WinRM
net stop workfolderssvc
net stop WwanSvc
net stop XblAuthManager
net stop XblGameSave
net stop XboxNetApiSvc